[tool.poetry]
package-mode = false
name = "younhapia"
version = "0.1.0"
description = "The API backend server for DevHolics projects"
authors = ["Joonhyung Shin <joon46551@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
Django = "^5.0.4"
djangorestframework = "^3.15.1"
psycopg = {extras = ["c"], version = "^3.1.18"}
django-allauth = "^0.61.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
