# Generated by Django 5.1.4 on 2024-12-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kkappu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kkappuimage",
            name="description",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="kkappudocument",
            name="file_size",
            field=models.PositiveBigIntegerField(editable=False, null=True),
        ),
    ]
